### ISSUE TITLE
Let scraping resume after erroring out

### ISSUE THREAD

**Issue by fgregg** [datamade/municipal-scrapers-us#14]
We can pass command line args into bills scarpe, so lets' pass in a trigger to resume scraping at near the point of last error.

Hmm... what happens to data that has been scraped, so far, when a scraper throws an exception @paultag?

**Comment by paultag** [comment]
nothing, but it will purge last run's data on start up

in theory the cache solves this, but it might not if you need to POST -- what's the context here?

**Comment by fgregg** [comment]
Legistar uses extensive use of POST, so the scrapelib's caching effectively
does nothing for us. Maybe that's the place fix it. It seems like scrapelib
could cache using the base url and post payload content as the key.

**Comment by fgregg** [comment]
oh... maybe never mind on this thing. One line fix. and I dramatically improved my hit rate. Closing for now. Thanks for being a rubber duck: http://en.wikipedia.org/wiki/Rubber_duck_debugging

**Comment by paultag** [comment]
I've got a rubber duck on my desk! Any time, @fgregg!

On Fri, Jan 16, 2015 at 10:58 AM, Forest Gregg <notifications@github.com>
wrote:

> Closed #14 <https://github.com/datamade/municipal-scrapers-us/issues/14>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/municipal-scrapers-us/issues/14#event-220150816>
> .
>



-- 
:wq
