### ISSUE TITLE
What is the difference between "Name" and "Title" of a piece of legislation

### ISSUE THREAD

**Issue by fgregg** [datamade/municipal-scrapers-us#17]
http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=2386648&GUID=1248F3A5-6EFC-478F-BFE6-3126120BDB30

Kind of seems like "Title" is actually the description.

paging @davidmooreppf

**Comment by davidmooreppf** [comment]
Checked with our primary contact at Council, can check with a legislative staffer if there's a technical legislative handbook w/ definitions or parameters or whatever. But yeah, that seems to be the case in NYC leg. objects.

**Comment by davidmooreppf** [comment]
Contact at Council forwarded to questions (also re: start dates) to a legislative attorney there. Will update.

**Comment by davidmooreppf** [comment]
Reply from att'y: 

Name field: Created by Council legislative administrative staff.
 
Title field: There are some legal rules governing titles. Every bill and resolution has a title. The title is neither consolidated nor unconsolidated law. The title of a bill must “briefly refer to the subject matter,” and both the title and the bill must cover a single subject. Rule 6.00, Rules of the Council; Charter § 32; N.Y. Mun. Home Rule Law § 20(3).

**Comment by fgregg** [comment]
Okay, I'm going to have "name" be the OCD title and "title" be an abstract.
