### ISSUE TITLE
Data modeling help

### ISSUE THREAD

**Issue by fgregg** [datamade/municipal-scrapers-us#18]
Hi @davidmooreppf, the scraper does a fair amount of data modeling that could use your expertise. First, we classify legislation type:

https://github.com/datamade/municipal-scrapers-us/blob/master/nyc/bills.py#L103-L112

The capitalized terms are the types as they appear in NYC legistar, the lower case terms are the types that are opencivicdata knows about: https://github.com/opencivicdata/python-opencivicdata-django/blob/master/opencivicdata/common.py#L71-L90

For many of the NYC legislative types, there does not appear to be a corresponding class in OCD. These are given the `None` type. @davidmooreppf can you see if this looks correct.

Second, we do the same thing with bill action types:
https://github.com/datamade/municipal-scrapers-us/blob/master/nyc/bills.py#L115-L146

The bill actions that OCD knows about is here: https://github.com/opencivicdata/python-opencivicdata-django/blob/master/opencivicdata/common.py#L103-L128

Can you check to see if these look right.

**Comment by davidmooreppf** [comment]
Will check this afternoon - yeah figured we'd go over this.

**Comment by davidmooreppf** [comment]
So, I'm not a legislative expert but I can connect w/ attorneys in NYC and recommend national bodies, e.g. National League of Cities, that might be able to share a spreadsheet of types-of-legislative objects for OCD. Of course, individual cities & their Brigades will have local expertise, and Legistar will know more too. 

Re: the NYC terms you linked above, let's chat voice over how I can help? A few basic notes:

How was it decided that Introduction maps to "bill", and not "Intro"? Just wondering.

That list of ten types is clearly missing seven types that are included in the drop-down on [NYC legistar](http://legistar.council.nyc.gov/Legislation.aspx), e.g. Resolution. Are you asking me to make a recommendation on whether to capture all those types from NYC Legistar and thereby include them as types in OCD? I can prioritize certain types over others, e.g. Resolutions are often discussed in NYC.

I'll look to get more info from you on how many new types of legslation we want to put into OCD now, versus adding them city-by-city. Ping me chat at your convenience, I'm g-chat davidrussellmoore, adding you now in my Adium.

**Comment by davidmooreppf** [comment]
Just going through the 17 types in NYC Legistar, then, aiming for same format - so the Legistar types are there, at least, to change or edit later if an attorney suggests so - it's possible that some of these map to OCD types and I just don't know about the technical language now - anyway: 

BILL_TYPES = {'City Agency Report': None, 
'Commissioner of Deeds': None, 
'Communication': None, 
'Introduction': 'bill',
'Land Use Application': None, 
'Land Use Call-Up': None,
'Local Law': None, 
'Local Laws 2014': None, 
'Local Laws 2015': None, 
'Mayor's Message': None, 
'Oversight': None, 
'Petition': None, 
'Resolution': 'resolution', 
'SLR': None, 
'Special Event': None, 
'Tour': None, 
'Town Hall Meeting': None}

... that covers the 17 existing types in current Legistar drop-down.

**Comment by fgregg** [comment]
Cool, and what about the action types?

**Comment by davidmooreppf** [comment]
Not seeing a comprehensive list or drop-down of action types on NYC Legistar, incl. advanced search, though I could ask Council for one if need be. So working off the list you linked above. 

Looking at the seven existing action types that correspond to "none", that seems correct for now. In any case, we'll link back to primary source URL on our legislative object pages.

I can't confirm that "sent to mayor by council" maps to "received by executive" - I could find out, but not necessary. 

How cool is 'Rcvd, Ord, Prnt, Fld by Council'.

**Comment by fgregg** [comment]
yeah, what does that last one even mean?

**Comment by davidmooreppf** [comment]
Oh I just assume it's shorthand for Received, Ordered, Printed, Filed". It's not like everyone walks around lower Manhattan saying, "can you RODF that to Council?" 

We mostly make anticipatory jokes about the puns on the front covers of tomorrow's NY Post & Daily News.

**Comment by fgregg** [comment]
so that means 'filing' ?

**Comment by davidmooreppf** [comment]
Oh I'm just guessing so. I could find out if helpful. In any case, I'd hear the "Fld" Mid-Atlantic dialect with my Midwestern brain anyway.
