### ISSUE TITLE
OCD does not display two new board members

### ISSUE THREAD

**Issue by reginafcompton** [datamade/municipal-scrapers-us#22]
The folks at LA Metro added two new board members to legistar: Kathryn Barger and Janice Hahn

https://metro.legistar.com/DepartmentDetail.aspx?ID=28529&GUID=44319A1A-B2B7-48CC-B857-ADCE9064573B&Mode=MainBody

They do not appear in the OCD API:

http://ocd.datamade.us/ocd-organization/42e23f04-de78-436a-bec5-ab240c1b977c/

**Comment by fgregg** [comment]
Hi @reginafcompton sorry for the confusion. please open future issues on https://github.com/opencivicdata/scrapers-us-municipal

**Comment by reginafcompton** [comment]
@fgregg Ah, okay! Let me know when you resolve this.

**Comment by fgregg** [comment]
This has been fixed
